export const TEXT_NOT_EMPTY = /^$|\s+/;
export const STRIP_MD =
	/([_*])(?<!(?:\1|\w).)(?![_*\s])(.*?[^_*\s])(?=\1)([_*])(?!\w|\3)/g;
export const STRIP_MD_LINK = /(?:__|[*#])|\[(.*?)\]\(.*?\)/g;
export const MD_BLOCKQUOTE = /(^> ?)/gm;
export const MD_ORDERED_LIST = /(^(\d+\.)(\s))+/gm;
export const MD_UNORDERED_LIST_DASH = /(^- )/gm;
export const MD_UNORDERED_LIST_ASTRIEK = /(\n\*.)/gm;
export const GET_MD_LINKS = /\[([^[\]]*)\]\((.*?)\)/gm;
