name: "Setup E2E Env"
on:
  workflow_call:
    inputs:
      test_name:
        required: true
        type: string
      device_type:
        required: true
        type: string
jobs:
  E2E:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Cache build
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/*.[jt]sx?') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-
      - name: Cache playwright binaries
        uses: actions/cache@v3
        id: playwright-cache
        with:
          path: |
            ~/.cache/ms-playwright
          key: cache-playwright-linux-1.19.2
      - name: Install dependencies
        run: yarn install
      - name: Next build
        run: yarn build
      - name: Install playwright browsers
        run: npx playwright install --with-deps
      - name: Run E2E tests
        run: yarn test:e2e:ci ${{inputs.test_name}} --project="${{inputs.device_type}}"
