name: "Browser"

on: [push]

jobs:
  e2e_desktop:
    name: Desktop Chrome
    uses: ./.github/workflows/e2e.yml
    with:
      test_name: articles navigation
      device_type: "Desktop Chrome"

  e2e_desktop_glossary:
    name: Desktop Chrome / Glossary
    uses: ./.github/workflows/e2e.yml
    with:
      test_name: Glossary
      device_type: "Desktop Chrome"

  e2e_desktop_annotations:
    name: Desktop Chrome / Annotations
    uses: ./.github/workflows/e2e.yml
    with:
      test_name: Annotations
      device_type: "Desktop Chrome"

  e2e_mobile_glossary:
    name: Mobile Chrome / Glossary
    uses: ./.github/workflows/e2e.yml
    with:
      test_name: Glossary
      device_type: "Mobile Chrome"

  e2e_mobile_annotations:
    name: Mobile Chrome / Annotations
    uses: ./.github/workflows/e2e.yml
    with:
      test_name: Annotations
      device_type: "Mobile Chrome"
